config/routes.rb
Rails.application.routes.draw do
  root 'subs#index'
  # get 'sub/index'
  # get 'sub/edit'
  # get 'sub/show'
  # get 'sub/new'
  # post 'sub/create'
  resources :subs do
    resources :topics  
      # bad practice
      # resources :comments do
      #   resources :likes
      # end
    # '/subs/:sub_id/topics'
    # /subs/1/topics
    # /subs/:sub_id/topics/:id
    # /subs/2/topics/1
  end
  resources :topics do
    resources :comments
  end
  # resources :pictures
  # http verb  'url pattern', to: 'controller#action'
    #  :id   placeholder for id 
    # get '/people', to: 'people#index'
    # "/subs/3"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :name, presence: true
  has_many :topics, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
lass CommentsController < ApplicationController
  before_action :set_topic
  before_action :set_comment, only: [
    :show, :edit, :update, :destroy]
  def index
    @comments = @topic.comments
  end
  def show
  end
  def new
    @comment = @topic.comments.new 
    render partial: "form"
  end
  def create
    @comment = @topic.comments.new(comment_params)
    if @comment.save
      redirect_to [@topic, @comment]
    else
      render :new
    end
  end
  def edit
    render partial: "form"
  end
  def update
    if @comment.update(comment_params)
      redirect_to [@topic, @comment]
    else
      render :edit
    end
  end
  def destroy
    @comment.destroy
    redirect_to topic_comments_path(@topic)
  end
  private
    def comment_params
      params.require(:comment).permit(:author, :body)
    end
    def set_comment
      @comment = Comment.find(params[:id])
    end
    def set_topic
      @topic = Topic.find(params[:topic_id])
    end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  # skinny controllers  actions
  # fat models  logic
  #              http verb
  # C   create     POST
  # R   read       GET
  # U   update     PUT / PATCH
  # D   destroy    DELETE
  # by default the controller actions return html
  # XML, JSON 
  # then go to a action that does
  # index - show all of records 
  # # READ / GET 
  #   def index
  #     @model_names = Model_name.all
  #   end
  # show - show a single record, id 
  #   def show
  #     @model_name = Model_name.find(params[:id])
  #   end
  # new - new form for a new record, create record in memory .new
  #   def new
  #     @model_name = Model_name.new
  #   end
  # edit - edit form for a record, id, update record in memory 
  #   def edit
  #     @model_name = Model_name.find(params[:id])
  #   end
  # create - create record in database
  #   Create / POST 
  #   def create
  #     @model_name = Model_name.new(model_name_params)
  #     if @model_name.save 
  #       do something or go somewhere 
  #     else
  #       render :new
  #     end
  #   end
  #   .
  #   .
  #   .
  #   private
  #     def model_name_params
  #       params.require(:model_name).permit(:attr, :everythingtable has)
  #     end
  # update - update the record in your database
  #   Update / PUT
  #   def update
  #     @model_name = Model_name.find(params[:id])
  #     if @model_name.update(model_name_params)
  #       do something or go somewhere
  #     else
  #       render :edit
  #     end
  #   end
  # destroy - delete the record from the database, id 
  #   destroy / DELETE
  #   def destroy
  #     @model_name = Model_name.find(params[:id])
  #     @model_name.destroy
  #     send somewhere
  #     or 
  #     Model_name.find(params[:id]).destroy
  #     send somewhere
  #   end
  # callback logic at a certain time
  # before_action
  # after_action
  # skip_before_action
  # before_action :method_name
  # before_action :method_name, only: [:show, :update, :edit, :destroy]
  # before_action :method_name, except: [:index, :new, :create]
  # GET
  def index
    @subs = Sub.all
    # render index.html.erb
  end
  def show
    @sub = Sub.find(params[:id])
    # render show.html.erb
  end
  def new
    @sub = Sub.new
    render partial: 'form'
    # render new.html.erb
  end
  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to subs_path
    else
      render :new 
    end
  end
  def edit
    @sub = Sub.find(params[:id])
    render partial: 'form'
    # render edit.html.erb edit form
  end
  def update
            # Look up a record return the record 
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to subs_path
    else
      render :edit
    end
  end
  def destroy
    # @sub = Sub.find(params[:id])
    # @sub.destroy
    # redirect_to subs_path
    # or
    Sub.find(params[:id]).destroy
    redirect_to subs_path
  end
  private 
    def sub_params
      # { sub: { name: 'puppies', age: 12, pass: select * password from user } }
      params.require(:sub).permit(:name)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :set_sub
  def index
   @topics = @sub.topics
  end
  def show
  end
  def new
    @topic = @sub.topics.new
    render partial: "form"
  end
  def create
    @topic = @sub.topics.new(topic_params)
    if @topic.save
      redirect_to [@sub, @topic]
    else
      render :new
    end
  end
  def edit
    render partial: "form"
  end
  def update
    if @topic.update(topic_params)
      redirect_to [@sub, @topic]
    else
      render :edit
    end
  end
  def destroy 
    @topic.destroy
    redirect_to sub_topics_path(@sub)
  end
  private
    def topic_params
      params.require(:topic).permit(:title, :body)
    end
    def set_topic
      @topic = Topic.find(params[:id])
    end
    def set_sub
      @sub = Sub.find(params[:sub_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>All Comments</h1>
<% @comments.each do |comment| %>
  <%= link_to comment.author, [@topic, @comments] %>
<% end %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<h1><%= @sub.id ? 'Edit sub' : 'Create Sub' %> </h1>
<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <%= f.submit %>
<% end %>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1> All Subs </h1>

<ul>
  <% @subs.each do |sub| %>
    <li>
      <%= link_to sub.name, sub %>
    </li>
  <% end %>
</ul>
<%= link_to 'New Sub', new_sub_path %>

app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View all Subs', subs_path %>
<br />
<%= link_to 'View Topics', sub_topics_path(@sub) %>
<br />
<%= link_to 'Edit Sub', edit_sub_path(@sub) %>
<br />
<%= link_to 'Delete Sub', @sub, method: :delete %>

app/views/topics/_form.html.erb
<h1><%= @topic.id ? "Edit Topic" : "Create Topic" %></h1>
<hr />
<%= form_for [@sub, @topic] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>

  <%= f.label :body%>
  <%= f.text_area :body, required: true %>
  
  <%= f.submit %>
<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1><%= @sub.name %> Topics</h1>
<ul>
  <% @topics.each do |topic| %>
    <li>
      <%= link_to topic.title, [@sub, topic] %>
    </li>
  <% end %>
</ul>
<%= link_to 'Create new topic', new_sub_topic_path(@sub) %>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1><%= @sub.name %> <%= @topic.title %></h1>
<p><%= @topic.body %></p>
<%= link_to 'Edit Topic', edit_sub_topic_path([@sub, @topic]) %>
<%= link_to 'Delete Topic', [@sub, @topic], method: :delete %>
<%= link_to 'Back to topics', sub_topics_path(@sub) %>
<%# link_to 'View Comments', topic_comments_path(@topic) %>